_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
#gpus: 1 # Specify GPU by CUDA_VISIBLE_DEVICES=0 
# accelerator: ddp
min_epochs: 1
max_epochs: 1
log_every_n_steps: 5
# weights_summary: null
# resume_from_checkpoint: null
precision : 16

inference_mode: False # Disable this when making grad cam inference

num_sanity_val_steps : 0 # This does not work with dp, only with ddp
# val_check_interval: 0.0
check_val_every_n_epoch : 1
benchmark: True
overfit_batches: False
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0

# profiler : "simple"