_target_: models.denoising_ae_3D.DAE_3D

cfg:

  name: DAE_3D

  ## Data 
  unet_model: UNET #RESIDUALUNET
  batch_size: ${datamodule.cfg.batch_size}
  
  in_channels: 1
  out_channels: 1
  final_sigmoid: False
  f_maps: 64
  layer_order: gcr
  num_groups: 8
  num_levels: 4
  is_segmentation: False
  conv_padding: 1

  class_weights: [0.32,1]
 
  lossStrategy: 'mean'
  lr: ${datamodule.cfg.lr}

  save_sample_path: ${model_output_dir}/${hydra:job.name}/${current_fold}/

  plot_save_path: ${plot_save_dir}/${hydra:job.name}/${current_fold}/

  plot_save_path_cv: ${plot_save_dir}/${hydra:job.name}/

  
