_target_: models.densenet.DenseNetClassifier

cfg:
  name: DenseNetClassifier
  model_name: 3D DenseNet264
  ## Data 
  batch_size: ${datamodule.cfg.batch_size}
  spatialDims: 3D
  model_depth: 264

  class_weights: [0.32,1]
 
  lossStrategy: 'mean'
  lr: ${datamodule.cfg.lr}
  
  enable_gradcam: False
  method: ggcam
  save_sample_path: ${model_output_dir}/${hydra:job.name}/${current_fold}/
  attention_folder: ${plot_save_dir}/attention_maps/${hydra:job.name}/${current_fold}/
  plot_save_path: ${plot_save_dir}/${hydra:job.name}/${current_fold}/

  plot_save_path_cv: ${plot_save_dir}/${hydra:job.name}/

  






  




