_target_: models.resnet.ResNetClassifer

cfg:
  name: ResNetClassifer
  model_name: 3D ResNet50
  ## Data 
 
  batch_size: ${datamodule.cfg.batch_size}
  spatialDims: 3D
  model_depth: 50

  #class_weights: [0.32,1]
  class_weights: [1,1]
  lossStrategy: 'mean'
  enable_gradcam: False
  attention_folder: ${plot_save_dir}/attention_maps/${hydra:job.name}/${current_fold}/
  method: ggcam
  lr: ${datamodule.cfg.lr}
  

  save_sample_path: ${model_output_dir}/${hydra:job.name}/${current_fold}/

  plot_save_path: ${plot_save_dir}/${hydra:job.name}/${current_fold}/

  plot_save_path_cv: ${plot_save_dir}/${hydra:job.name}/

  






  




