_target_: models.resunet_3D.ResUNetClassifer

cfg:
  name: ResUNetClassifer
  model_name: 3DResUNet
  ## Data 
  
  batch_size: ${datamodule.cfg.batch_size}
  model_depth: 18

  #class_weights: [0.3,1]
  class_weights: [0.83,1.24]

  enable_gradcam: False
  attention_folder: ${plot_save_dir}/attention_maps/${hydra:job.name}/${current_fold}/
  method: ggcam

  in_channels : 1
  out_channels: 1
  final_sigmoid: False
  n_classes : 2
  f_maps : 64
  layer_order : 'gcr'
  num_groups : 8
  num_levels : 4
  is_segmentation : False
  conv_kernel_size : 3
  pool_kernel_size: 2
  conv_padding: 1
  is3d: True
  classify: False
  
 
  lossStrategy: 'mean'
  lr: ${datamodule.cfg.lr}

  save_sample_path: ${model_output_dir}/${hydra:job.name}/${current_fold}/

  plot_save_path: ${plot_save_dir}/${hydra:job.name}/${current_fold}/

  plot_save_path_cv: ${plot_save_dir}/${hydra:job.name}/



  