_target_: datamodules.data_mod.ParanasalClassificationDataModule

cfg:
  name: ParanasalClassificationDataModule
  
  dimension:  64
  batch_size: 16
  num_workers: 4
  crop_size: 35
  samples_per_patient: 1 #Number of maxillary sinus volumes to consider per patient
  lr : 0.0001
  label_group:  [[0],[1,2,3,4]]
  augmentations: False
  trainset: /home/debayan/Desktop/MRI_HCHS/CARS-labelled-x-constant/splits/crop_size_35_std_factor_1/fold_${current_fold}/train.csv
  valset: /home/debayan/Desktop/MRI_HCHS/CARS-labelled-x-constant/splits/crop_size_35_std_factor_1/fold_${current_fold}/val.csv
  testset: /home/debayan/Desktop/MRI_HCHS/CARS-labelled-x-constant/splits/crop_size_35_std_factor_1/fold_${current_fold}/test.csv
  one_patient_id: NULL
  modelpath: None

  