_target_: datamodules.data_mod.ParanasalClassificationDataModule

cfg:
  name: ParanasalClassificationDataModule
  
  dimension:  64
  batch_size: 16
  num_workers: 4
  crop_size: 999
  samples_per_patient: 1 #Number of maxillary sinus volumes to consider per patient
  lr : 0.0001
  label_group:  [[0],[1,2,3,4]] #0 normal #1 mucosal thickening #2 polyps #3 cysts #4 fully occupied 
  augmentations: True
  trainset: /home/debayan/Desktop/MRI_HCHS/JAMA-labelled-1000/splits_corrected/crop_size_35_40_45_50_55_60_65_70_75_80__std_factor_1/fold_${current_fold}/train.csv
  valset: /home/debayan/Desktop/MRI_HCHS/JAMA-labelled-1000/splits_corrected/crop_size_35_40_45_50_55_60_65_70_75_80__std_factor_1/fold_${current_fold}/val.csv
  testset:  /home/debayan/Desktop/MRI_HCHS/JAMA-labelled-1000/splits_corrected/crop_size_35_40_45_50_55_60_65_70_75_80__std_factor_1/fold_${current_fold}/test_75.csv
  one_patient_id: NULL #['sub-9acb1fd7']
  modelpath: None

  