_target_: datamodules.data_mod.ParanasalInferenceDataModule

cfg:
  name: ParanasalInferenceDataModule
  
  dimension:  64
  batch_size: 16
  num_workers: 4

  samples_per_patient: 20
  lr : 0.0001
  
  augmentations: False
  trainset: /media/debayan/c7b64c90-ca4e-4192-8ed9-8fea1d005196/MRI_HCHS/dataset/JAMA_unlabelled/split_cc_40.txt
  valset: /media/debayan/c7b64c90-ca4e-4192-8ed9-8fea1d005196/MRI_HCHS/dataset/JAMA_unlabelled/split_cc_40.txt
  testset: /media/debayan/c7b64c90-ca4e-4192-8ed9-8fea1d005196/MRI_HCHS/dataset/JAMA_unlabelled/split_cc_40.txt

  modelpath: None

  