_target_: datamodules.data_mod.ParanasalAEDataModule

cfg:

  name: ParanasalAEDataModule
  
  dimension:  64
  batch_size: 16
  num_workers: 4
  crop_size: 65
  noise_std: 0.6
  samples_per_patient: 1 #Number of maxillary sinus volumes to consider per patient
  lr : 0.0008
  label_group:  [[0],[1,2,3,4]] #0 normal #1 mucosal thickening #2 polyps #3 cysts #4 fully occupied 
  augmentations: True
  trainset: /home/debayan/Desktop/MRI_HCHS/JAMA-unlabelled-1000-corrected/splits/split_cc_65.txt
  valset: /home/debayan/Desktop/MRI_HCHS/JAMA-unlabelled-1000-corrected/splits/val.txt
  testset: /home/debayan/Desktop/MRI_HCHS/JAMA-unlabelled-1000-corrected/splits/val.txt
  one_patient_id: NULL #['sub-9acb1fd7']
  modelpath: None
  ae_model: AE_3D_cc_65_ls_512
  median_filter: MF_0


  